/*
 * CODENVY CONFIDENTIAL
 * __________________
 *
 * [2012] - [2013] Codenvy, S.A.
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Codenvy S.A. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Codenvy S.A.
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Codenvy S.A..
 */
package org.exoplatform.ide.extension.gadget.server.opensocial.service;

import org.exoplatform.ide.extension.gadget.server.opensocial.model.Activity;

import java.util.List;

/**
 * Service to manipulate with OpenSocial Activity data, which represents a short summary or notification of a timestamped event.
 *
 * @author <a href="mailto:zhulevaanna@gmail.com">Ann Zhuleva</a>
 * @version $Id: Nov 19, 2010 $
 */
public interface ActivityService {
    /**
     * Request for Activities.
     *
     * @param userId
     *         user ID of the person whose activities are to be returned
     * @param groupId
     *         group ID of the group of users whose activities are to be returned
     * @param appId
     *         Specifies that the response should only contain activities generated by the given appId (optional)
     * @param activityIds
     *         list of individual activities to include in the response (optional)
     * @return
     */
    List<Activity> getActivities(String userId, String groupId, String appId, List<String> activityIds);

    /**
     * Retrieve a list of supported Activity fields.
     *
     * @return {@link List{@link String} activity fields
     */
    List<String> getActivityFields();

    /**
     * Create an Activity.
     *
     * @param userId
     *         user ID of the person to associate the activity with
     * @param activity
     *         activity to associate with the given user
     * @return {@link Activity} created activity
     */
    Activity createActivity(String userId, Activity activity);

    /**
     * Request to update an Activity.
     *
     * @param userId
     *         user ID of the person the activity is associated with
     * @param activity
     *         activity to update
     * @return {@link Activity} updated activity
     */
    Activity updateActivity(String userId, Activity activity);

    /**
     * Delete activity.
     *
     * @param userId
     *         user ID(s) of the person the activity is associated with
     * @param activity
     *         activity to delete
     */
    void deleteActivity(String userId, Activity activity);
}
