/*
 * Copyright (C) 2012 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.exoplatform.ide.client.framework.navigation.event;

import com.google.gwt.event.shared.GwtEvent;
import com.google.gwt.event.shared.HandlerManager;

/**
 * Generated by pressing on Show/Hide Hidden Files item in View menu.
 * Listening this event IDE shows or hides hidden files.
 *
 * @author <a href="mailto:azatsarynnyy@exoplatform.org">Artem Zatsarynnyy</a>
 * @version $Id: ShowHiddenFilesEvent.java Mar 30, 2012 12:25:40 PM azatsarynnyy $
 */
public class ShowHideHiddenFilesEvent extends GwtEvent<ShowHideHiddenFilesHandler> {

    /** Type class used to register events with the {@link HandlerManager}. */
    public static final GwtEvent.Type<ShowHideHiddenFilesHandler> TYPE = new GwtEvent.Type<ShowHideHiddenFilesHandler>();

    /** <code>true</code> when hidden files are shown. */
    private boolean filesAreShown;

    /**
     * Creates a new event to show or hide hidden files.
     *
     * @param showFiles
     *         if <code>true</code> - show hidden files,
     *         if <code>false</code> - hide hidden files
     */
    public ShowHideHiddenFilesEvent(boolean showFiles) {
        this.filesAreShown = showFiles;
    }

    /** @see com.google.gwt.event.shared.GwtEvent#getAssociatedType() */
    @Override
    public Type<ShowHideHiddenFilesHandler> getAssociatedType() {
        return TYPE;
    }

    /** @see com.google.gwt.event.shared.GwtEvent#dispatch(com.google.gwt.event.shared.EventHandler) */
    @Override
    protected void dispatch(ShowHideHiddenFilesHandler handler) {
        handler.onShowHideHiddenFiles(this);
    }

    /**
     * Checks whether the files are hidden.
     *
     * @return <code>true</code> when hidden files are shown,
     *         <code>false</code> when hidden files are not shown
     */
    public boolean isFilesShown() {
        return filesAreShown;
    }
}
