/*
 * CODENVY CONFIDENTIAL
 * __________________
 *
 * [2012] - [2013] Codenvy, S.A.
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Codenvy S.A. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Codenvy S.A.
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Codenvy S.A..
 */
package org.exoplatform.ide.client.framework.navigation.event;

import com.google.gwt.event.shared.GwtEvent;
import com.google.gwt.event.shared.HandlerManager;

/**
 * Generated by pressing on Show/Hide Hidden Files item in View menu.
 * Listening this event IDE shows or hides hidden files.
 *
 * @author <a href="mailto:azatsarynnyy@exoplatform.org">Artem Zatsarynnyy</a>
 * @version $Id: ShowHiddenFilesEvent.java Mar 30, 2012 12:25:40 PM azatsarynnyy $
 */
public class ShowHideHiddenFilesEvent extends GwtEvent<ShowHideHiddenFilesHandler> {

    /** Type class used to register events with the {@link HandlerManager}. */
    public static final GwtEvent.Type<ShowHideHiddenFilesHandler> TYPE = new GwtEvent.Type<ShowHideHiddenFilesHandler>();

    /** <code>true</code> when hidden files are shown. */
    private boolean filesAreShown;

    /**
     * Creates a new event to show or hide hidden files.
     *
     * @param showFiles
     *         if <code>true</code> - show hidden files,
     *         if <code>false</code> - hide hidden files
     */
    public ShowHideHiddenFilesEvent(boolean showFiles) {
        this.filesAreShown = showFiles;
    }

    /** @see com.google.gwt.event.shared.GwtEvent#getAssociatedType() */
    @Override
    public Type<ShowHideHiddenFilesHandler> getAssociatedType() {
        return TYPE;
    }

    /** @see com.google.gwt.event.shared.GwtEvent#dispatch(com.google.gwt.event.shared.EventHandler) */
    @Override
    protected void dispatch(ShowHideHiddenFilesHandler handler) {
        handler.onShowHideHiddenFiles(this);
    }

    /**
     * Checks whether the files are hidden.
     *
     * @return <code>true</code> when hidden files are shown,
     *         <code>false</code> when hidden files are not shown
     */
    public boolean isFilesShown() {
        return filesAreShown;
    }
}
