/*
 * Copyright (C) 2010 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.exoplatform.ide.client.module.edit;

import com.google.gwt.event.shared.HandlerManager;

import org.exoplatform.gwtframework.commons.dialogs.Dialogs;
import org.exoplatform.gwtframework.commons.exception.ExceptionThrownEvent;
import org.exoplatform.gwtframework.commons.rest.AsyncRequestCallback;
import org.exoplatform.ide.client.framework.editor.event.EditorActiveFileChangedEvent;
import org.exoplatform.ide.client.framework.editor.event.EditorActiveFileChangedHandler;
import org.exoplatform.ide.client.framework.editor.event.EditorFileClosedEvent;
import org.exoplatform.ide.client.framework.settings.ApplicationSettings.Store;
import org.exoplatform.ide.client.framework.settings.event.ApplicationSettingsReceivedEvent;
import org.exoplatform.ide.client.framework.settings.event.ApplicationSettingsReceivedHandler;
import org.exoplatform.ide.client.framework.userinfo.UserInfo;
import org.exoplatform.ide.client.framework.userinfo.event.UserInfoReceivedEvent;
import org.exoplatform.ide.client.framework.userinfo.event.UserInfoReceivedHandler;
import org.exoplatform.ide.client.framework.vfs.File;
import org.exoplatform.ide.client.framework.vfs.Item;
import org.exoplatform.ide.client.framework.vfs.VirtualFileSystem;
import org.exoplatform.ide.client.framework.vfs.callback.ItemLockCallback;
import org.exoplatform.ide.client.framework.vfs.event.ItemLockResultReceivedEvent;
import org.exoplatform.ide.client.framework.vfs.event.ItemLockResultReceivedHandler;
import org.exoplatform.ide.client.framework.vfs.event.ItemUnlockedEvent;
import org.exoplatform.ide.client.module.edit.event.LockFileEvent;
import org.exoplatform.ide.client.module.edit.event.LockFileHandler;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Handler for processing events, generated by Lock/Unlock button on toolbar.
 * Handles events, that are needed for correct display on Lock/Unlock button,
 * when active file changed.
 * 
 * @author <a href="mailto:oksana.vereshchaka@gmail.com">Oksana Vereshchaka</a>
 * @version $Id:
 *
 */
public class LockUnlockFileHandler implements LockFileHandler, UserInfoReceivedHandler, ItemLockResultReceivedHandler,
EditorActiveFileChangedHandler, ApplicationSettingsReceivedHandler
{

   private HandlerManager eventBus;

   private Map<String, String> lockTokens;
   
   private UserInfo userInfo;
   
   private File activeFile;

   public LockUnlockFileHandler(HandlerManager eventBus)
   {
      this.eventBus = eventBus;

      this.eventBus.addHandler(LockFileEvent.TYPE, this);
      this.eventBus.addHandler(UserInfoReceivedEvent.TYPE, this);
      this.eventBus.addHandler(EditorActiveFileChangedEvent.TYPE, this);
      this.eventBus.addHandler(ItemLockResultReceivedEvent.TYPE, this);
      this.eventBus.addHandler(ApplicationSettingsReceivedEvent.TYPE, this);
   }

   /**
    * @see org.exoplatform.ide.client.framework.editor.event.EditorFileClosedHandler#onEditorFileClosed(org.exoplatform.ide.client.framework.editor.event.EditorFileClosedEvent)
    */
   public void onEditorFileClosed(EditorFileClosedEvent event)
   {
      String lockToken = lockTokens.get(event.getFile().getHref());
      if(event.getFile().isNewFile())
      {
         return;
      }
      
      if (lockToken != null)
      {
         VirtualFileSystem.getInstance().unlock(event.getFile(), lockToken, new AsyncRequestCallback<Item>()
         {
            
            @Override
            protected void onSuccess(Item result)
            {
               eventBus.fireEvent(new ItemUnlockedEvent(result)); 
            }
            
            @Override
            protected void onFailure(Throwable exception)
            {
               eventBus.fireEvent(new ExceptionThrownEvent("Service is not deployed."));               
            }
         });
      }
   }

   /**
    * @see org.exoplatform.ide.client.model.settings.event.ApplicationSettingsReceivedHandler#onApplicationSettingsReceived(org.exoplatform.ide.client.model.settings.event.ApplicationSettingsReceivedEvent)
    */
   public void onApplicationSettingsReceived(ApplicationSettingsReceivedEvent event)
   {
      if (event.getApplicationSettings().getValueAsMap("lock-tokens") == null)
      {
         event.getApplicationSettings().setValue("lock-tokens", new LinkedHashMap<String, String>(), Store.COOKIES);
      }

      lockTokens = event.getApplicationSettings().getValueAsMap("lock-tokens");
   }

   /**
    * @see org.exoplatform.ide.client.module.edit.event.LockFileHandler#onLockFile(org.exoplatform.ide.client.module.edit.event.LockFileEvent)
    */
   public void onLockFile(LockFileEvent event)
   {
      if (event.isLockFile())
      {
         VirtualFileSystem.getInstance().lock(activeFile, 600, userInfo.getName(), new ItemLockCallback()
         {
            @Override
            protected void onSuccess(ItemLockData result)
            {
               eventBus.fireEvent(new ItemLockResultReceivedEvent(result.getItem(), result.getLockToken(), null));
            }

            @Override
            protected void onFailure(Throwable exception)
            {
               ItemLockResultReceivedEvent event =
                  new ItemLockResultReceivedEvent(this.getResult().getItem(), this.getResult().getLockToken(),
                     "Service is not deployed.<br />Lock was not enforceable on this resource.");
               event.setException(exception);
               eventBus.fireEvent(event);
            }
         });
      }
      else
      {
         String lockToken = lockTokens.get(activeFile.getHref());
         if (lockToken != null)
         {
            VirtualFileSystem.getInstance().unlock(activeFile, lockToken, new AsyncRequestCallback<Item>()
            {
               
               @Override
               protected void onSuccess(Item result)
               {
                  eventBus.fireEvent(new ItemUnlockedEvent(result));
               }
               
               @Override
               protected void onFailure(Throwable exception)
               {
                  eventBus.fireEvent(new ExceptionThrownEvent("Service is not deployed."));                  
               }
            });
         }
      }
   }

   /**
    * @see org.exoplatform.ide.client.framework.userinfo.event.UserInfoReceivedHandler#onUserInfoReceived(org.exoplatform.ide.client.framework.userinfo.event.UserInfoReceivedEvent)
    */
   public void onUserInfoReceived(UserInfoReceivedEvent event)
   {
      userInfo = event.getUserInfo();
   }

   /**
    * @see org.exoplatform.ide.client.framework.vfs.event.ItemLockResultReceivedHandler#onItemLockResultReceived(org.exoplatform.ide.client.framework.vfs.event.ItemLockResultReceivedEvent)
    */
   public void onItemLockResultReceived(ItemLockResultReceivedEvent event)
   {
      if (event.getException() != null)
      {
         Dialogs.getInstance().showError("Can't lock file <b>" + event.getItem().getName() + "</b>");
      }
   }

   /**
    * @see org.exoplatform.ide.client.framework.editor.event.EditorActiveFileChangedHandler#onEditorActiveFileChanged(org.exoplatform.ide.client.framework.editor.event.EditorActiveFileChangedEvent)
    */
   public void onEditorActiveFileChanged(EditorActiveFileChangedEvent event)
   {
      activeFile = event.getFile();
   }

}
