/*
 * Copyright (C) 2010 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.exoplatform.ide.client.edit.event;

import com.google.gwt.event.shared.GwtEvent;

/**
 * Generated by pressing on Lock/Unlock button on toolbar.
 * 
 * Listening this event, IDE locks or unlocks active file.
 * 
 * Created by The eXo Platform SAS .
 * 
 * @author <a href="mailto:oksana.vereshchaka@gmail.com">Oksana Vereshchaka</a>
 * @version $Id:
 * 
 */
public class LockFileEvent extends GwtEvent<LockFileHandler>
{

   public static final GwtEvent.Type<LockFileHandler> TYPE = new GwtEvent.Type<LockFileHandler>();

   private boolean lockFile;

   /**
    * Creates new event to lock or unlock file.
    * 
    * @param lockFile - if true - lock file, if false - unlock file
    */
   public LockFileEvent(boolean lockFile)
   {
      this.lockFile = lockFile;
   }

   @Override
   protected void dispatch(LockFileHandler handler)
   {
      handler.onLockFile(this);
   }

   @Override
   public com.google.gwt.event.shared.GwtEvent.Type<LockFileHandler> getAssociatedType()
   {
      return TYPE;
   }

   /**
    * Is lock or unlock file.
    * 
    * @return if true - file must be locked, false - file must be unlocked
    */
   public boolean isLockFile()
   {
      return lockFile;
   }

}
