/*
 * Copyright (C) 2012 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.exoplatform.ide.security.oauth;

import com.google.api.client.auth.oauth2.AuthorizationCodeFlow;
import com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl;
import com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl;
import com.google.api.client.auth.oauth2.Credential;
import com.google.api.client.auth.oauth2.TokenResponse;
import com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets;
import com.google.api.client.http.HttpParser;
import com.google.api.client.http.HttpRequest;
import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.json.JsonHttpParser;
import com.google.api.client.json.jackson.JacksonFactory;
import org.everrest.core.impl.provider.json.JsonException;
import org.everrest.core.impl.provider.json.JsonParser;
import org.everrest.core.impl.provider.json.JsonValue;
import org.everrest.core.impl.provider.json.ObjectBuilder;

import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.net.URLDecoder;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * @author <a href="mailto:andrew00x@gmail.com">Andrey Parfonov</a>
 * @version $Id: $
 */
public abstract class BaseOAuthAuthenticator implements OAuthAuthenticator
{
   public static GoogleClientSecrets loadClientSecrets(String configName) throws IOException
   {
      InputStream secrets = Thread.currentThread().getContextClassLoader().getResourceAsStream(configName);
      if (secrets != null)
      {
         // stream closed after parsing by JsonFactory.
         return GoogleClientSecrets.load(new JacksonFactory(), secrets);
      }
      throw new IOException("Cannot load client secrets. File '" + configName + "' not found. ");
   }

   protected final AuthorizationCodeFlow flow;
   private final Map<Pattern, String> redirectUrisMap;

   public BaseOAuthAuthenticator(AuthorizationCodeFlow flow, Set<String> redirectUris)
   {
      this.flow = flow;
      this.redirectUrisMap = new HashMap<Pattern, String>(redirectUris.size());
      for (String uri : redirectUris)
      {
         // Redirect URI may be in form urn:ietf:wg:oauth:2.0:oob os use java.net.URI instead of java.net.URL
         this.redirectUrisMap.put(Pattern.compile("([a-z0-9\\-]+\\.)?" + URI.create(uri).getHost()), uri);
      }
   }

   /**
    * Create authentication URL.
    *
    * @return URL for authentication
    */
   @Override
   public final String getAuthenticateUrl(String requestUrl, String userId)
   {
      AuthorizationCodeRequestUrl url = flow.newAuthorizationUrl().setRedirectUri(findRedirectUrl(requestUrl));
      StringBuilder state = new StringBuilder();
      addState(state);
      if (userId != null)
      {
         if (state.length() > 0)
         {
            state.append('&');
         }
         state.append("userId=");
         state.append(userId);
      }
      url.setState(state.toString());
      return url.build();
   }

   private String findRedirectUrl(String requestUrl)
   {
      final String requestHost;
      try
      {
         requestHost = new URL(requestUrl).getHost();
      }
      catch (MalformedURLException e)
      {
         throw new IllegalArgumentException("Invalid URL " + requestUrl);
      }
      for (Map.Entry<Pattern, String> e : redirectUrisMap.entrySet())
      {
         if (e.getKey().matcher(requestHost).matches())
         {
            return e.getValue();
         }
      }
      return null; // TODO : throw exception instead of return null ???
   }

   protected void addState(StringBuilder state)
   {
   }

   /**
    * Process callback request.
    *
    * @param requestUrl
    *    request URI. URI should contain authorization code generated by authorization server
    * @throws OAuthAuthenticationException
    *    if authentication failed or <code>requestUrl</code> does not contain required parameters, e.g. 'code'
    */
   @Override
   public final void callback(String requestUrl) throws OAuthAuthenticationException
   {
      AuthorizationCodeResponseUrl authorizationCodeResponseUrl = new AuthorizationCodeResponseUrl(requestUrl);
      final String error = authorizationCodeResponseUrl.getError();
      if (error != null)
      {
         throw new OAuthAuthenticationException("Authentication failed: " + error);
      }
      final String code = authorizationCodeResponseUrl.getCode();
      if (code == null)
      {
         throw new OAuthAuthenticationException("Missing authorization code. ");
      }

      try
      {
         final HttpParser parser = getParser();
         HttpResponse response = flow.newTokenRequest(code).setRequestInitializer(new HttpRequestInitializer()
         {
            @Override
            public void initialize(HttpRequest request) throws IOException
            {
               request.getHeaders().setAccept(parser.getContentType());
            }
         }).setRedirectUri(findRedirectUrl(requestUrl)).executeUnparsed();
         response.getRequest().addParser(parser);
         TokenResponse tokenResponse = response.parseAs(TokenResponse.class);
         String userId = getUserFromURL(authorizationCodeResponseUrl);
         if (userId == null)
         {
            User user = getUser(tokenResponse.getAccessToken());
            userId = user.getUserId();
         }
         flow.createAndStoreCredential(tokenResponse, userId);
      }
      catch (IOException ioe)
      {
         throw new OAuthAuthenticationException(ioe.getMessage());
      }
   }

   private String getUserFromURL(AuthorizationCodeResponseUrl authorizationCodeResponseUrl) throws IOException
   {
      String state = authorizationCodeResponseUrl.getState();
      if (!(state == null || state.isEmpty()))
      {
         String decoded = URLDecoder.decode(state, "UTF-8");
         String[] items = decoded.split("&");
         for (String str : items)
         {
            if (str.startsWith("userId="))
            {
               return str.substring(7, str.length());
            }
         }
      }
      return null;
   }

   /**
    * Get suitable implementation of HttpParser.
    *
    * @return instance  of HttpParser
    */
   protected HttpParser getParser()
   {
      return new JsonHttpParser(flow.getJsonFactory());
   }

   protected <U extends User> U getUser(String getUserUrl, Class<U> userClass) throws OAuthAuthenticationException
   {
      HttpURLConnection urlConnection = null;
      InputStream urlInputStream = null;

      try
      {
         urlConnection = (HttpURLConnection)new URL(getUserUrl).openConnection();
         urlInputStream = urlConnection.getInputStream();

         JsonParser parser = new JsonParser();
         parser.parse(urlInputStream);
         JsonValue jsonValue = parser.getJsonObject();

         return ObjectBuilder.createObject(userClass, jsonValue);
      }
      catch (JsonException e)
      {
         throw new OAuthAuthenticationException(e.getMessage(), e);
      }
      catch (IOException e)
      {
         throw new OAuthAuthenticationException(e.getMessage(), e);
      }
      finally
      {
         if (urlInputStream != null)
         {
            try
            {
               urlInputStream.close();
            }
            catch (IOException ignored)
            {
            }
         }

         if (urlConnection != null)
         {
            urlConnection.disconnect();
         }
      }
   }

   /**
    * Get oauth token.
    *
    * @param userId
    *    user
    * @return oauth token or <code>null</code>
    * @throws java.io.IOException
    *    if i/o error occurs when try to refresh expired oauth token
    */
   @Override
   public final String getToken(String userId) throws IOException
   {
      Credential credential = flow.loadCredential(userId);
      if (credential != null)
      {
         Long expirationTime = credential.getExpiresInSeconds();
         if (expirationTime != null && expirationTime < 0)
         {
            credential.refreshToken();
         }
         return credential.getAccessToken();
      }
      return null;
   }

   /**
    * Invalidate OAuth token for specified user.
    *
    * @param userId
    *    user
    * @return <code>true</code> if OAuth token invalidated and <code>false</code> otherwise, e.g. if user does not have
    *         token yet
    */
   @Override
   public final boolean invalidateToken(String userId)
   {
      Credential credential = flow.loadCredential(userId);
      if (credential != null)
      {
         flow.getCredentialStore().delete(userId, credential);
         return true;
      }
      return false;
   }
}
