/*
 * Copyright (C) 2012 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.exoplatform.ide.security.oauth;

import org.exoplatform.ide.security.shared.User;

import java.io.IOException;
import java.net.URL;
import java.util.List;

/**
 * Authentication service which allow get access token from OAuth provider site.
 *
 * @author <a href="mailto:vzhukovskii@exoplatform.com">Vladyslav Zhukovskii</a>
 * @version $Id: $
 */
public interface OAuthAuthenticator
{
   /**
    * Get the name of OAuth provider supported by current implementation.
    *
    * @return oauth provider name
    */
   String getOAuthProvider();

   /**
    * Create authentication URL.
    *
    * @param requestUrl
    *    URL of current HTTP request. This parameter required to be able determine URL for redirection after
    *    authentication. If URL contains query parameters they will be copy to 'state' parameter and returned to
    *    callback method.
    * @param userId
    *    user identifier. This parameter should be not <code>null</code> if user already authenticated in eXo IDE site
    *    but need to get OAuth access token to be able use some third party services. This parameter always
    *    <code>null</code> if third party OAuth provider used for authenticate user in eXo IDE.
    * @param scopes
    *    specify exactly what type of access needed
    * @return URL for authentication
    */
   String getAuthenticateUrl(URL requestUrl, String userId, List<String> scopes);

   /**
    * Process callback request.
    *
    * @param requestUrl
    *    request URI. URI should contain authorization code generated by authorization server
    * @param scopes
    *    specify exactly what type of access needed. This list must be exactly the same as list passed to the method
    *    {@link #getAuthenticateUrl(URL, String, java.util.List)}
    * @return id of authenticated user
    * @throws OAuthAuthenticationException
    *    if authentication failed or <code>requestUrl</code> does not contain required parameters, e.g. 'code'
    */
   String callback(URL requestUrl, List<String> scopes) throws OAuthAuthenticationException;

   /**
    * Get user info.
    *
    * @param accessToken
    *    oauth access token
    * @return user info
    * @throws OAuthAuthenticationException
    *    if fail to get user info
    */
   User getUser(String accessToken) throws OAuthAuthenticationException;

   /**
    * Get oauth token.
    *
    * @param userId
    *    user
    * @return oauth token or <code>null</code>
    * @throws java.io.IOException
    *    if i/o error occurs when try to refresh expired oauth token
    */
   String getToken(String userId) throws IOException;

   /**
    * Invalidate OAuth token for specified user.
    *
    * @param userId
    *    user
    * @return <code>true</code> if OAuth token invalidated and <code>false</code> otherwise, e.g. if user does not have
    *         token yet
    */
   boolean invalidateToken(String userId);
}
