# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1279547830);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1279547148);
user_pref("app.update.mode", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.dir", "C:\\Documents and Settings\\anya\\Мои документы\\Downloads");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.6");
user_pref("browser.startup.page", 0);
user_pref("dom.max_script_run_time", 1800);
user_pref("extensions.enabledItems", "{CAFEEFAC-0015-0000-0022-ABCDEFFEDCBA}:5.0.22,{CAFEEFAC-0016-0000-0018-ABCDEFFEDCBA}:6.0.18,jqs@sun.com:1.0,httpanalyzerffaddonv5@ieinspector.com:5.0.1,gwt-dev-plugin@google.com:1.0.7511,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.6");
user_pref("extensions.lastAppVersion", "3.6.6");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.autoScroll", false);
user_pref("gwt-dev-plugin.accessList", "192.168.0.29");
user_pref("intl.charsetmenu.browser.cache", "windows-1251, UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("skype_ff_toolbar_win.Layout", "6943");
user_pref("skype_ff_toolbar_win.firstlaunch", "1");
user_pref("skype_ff_toolbar_win.version", "3.3.0.3971");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1282139112);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
