# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1279615555);
user_pref("app.update.lastUpdateTime.background-update-timer", 1279615410);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1279615282);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1279615732);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1279614815);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1279614620);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.3");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.warnOnRestart", false);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.enabledItems", "{20a82645-c095-46ed-80e3-08825760534b}:1.1,gwt-dev-plugin@google.com:1.0.7511,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.3");
user_pref("extensions.lastAppVersion", "3.6.3");
user_pref("extensions.newAddons", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.autoScroll", false);
user_pref("general.useragent.extra.microsoftdotnet", "(.NET CLR 3.5.30729)");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("microsoft.CLR.auto_install", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1282206592);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
