/**
 * Copyright (C) 2009 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 11:22:32 AM EET 
//

package org.exoplatform.gwtframework.commons.wadl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.exoplatform.gwtframework.commons.xml.QName;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://research.sun.com/wadl/2006/10}doc" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://research.sun.com/wadl/2006/10}option" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://research.sun.com/wadl/2006/10}link" minOccurs="0"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fixed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="repeating" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="style" use="required" type="{http://research.sun.com/wadl/2006/10}ParamStyle" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}QName" default="xs:string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Param
{

   protected List<Doc> doc;

   protected List<Option> option;

   protected Link link;

   protected List<Object> any;

   protected String _default;

   protected String fixed;

   protected String id;

   protected String name;

   protected String path;

   protected Boolean repeating;

   protected Boolean required;

   protected ParamStyle style;

   protected QName type;

   protected String href;

   /**
    * Sets the value of the href property.
    */
   public String getHref()
   {
      return href;
   }

   /**
    * Sets the value of the href property.
    * 
    * @param href
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setHref(String href)
   {
      this.href = href;
   }

   private Map<QName, String> otherAttributes = new HashMap<QName, String>();

   /**
    * Gets the value of the doc property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the doc property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getDoc().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link Doc }
    * 
    * 
    */
   public List<Doc> getDoc()
   {
      if (doc == null)
      {
         doc = new ArrayList<Doc>();
      }
      return this.doc;
   }

   /**
    * Gets the value of the option property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the option property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getOption().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link Option }
    * 
    * 
    */
   public List<Option> getOption()
   {
      if (option == null)
      {
         option = new ArrayList<Option>();
      }
      return this.option;
   }

   /**
    * Gets the value of the link property.
    * 
    * @return
    *     possible object is
    *     {@link Link }
    *     
    */
   public Link getLink()
   {
      return link;
   }

   /**
    * Sets the value of the link property.
    * 
    * @param value
    *     allowed object is
    *     {@link Link }
    *     
    */
   public void setLink(Link value)
   {
      this.link = value;
   }

   /**
    * Gets the value of the any property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the any property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getAny().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link Object }
    * {@link Element }
    * 
    * 
    */
   public List<Object> getAny()
   {
      if (any == null)
      {
         any = new ArrayList<Object>();
      }
      return this.any;
   }

   /**
    * Gets the value of the default property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getDefault()
   {
      return _default;
   }

   /**
    * Sets the value of the default property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setDefault(String value)
   {
      this._default = value;
   }

   /**
    * Gets the value of the fixed property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getFixed()
   {
      return fixed;
   }

   /**
    * Sets the value of the fixed property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setFixed(String value)
   {
      this.fixed = value;
   }

   /**
    * Gets the value of the id property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getId()
   {
      return id;
   }

   /**
    * Sets the value of the id property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setId(String value)
   {
      this.id = value;
   }

   /**
    * Gets the value of the name property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getName()
   {
      return name;
   }

   /**
    * Sets the value of the name property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setName(String value)
   {
      this.name = value;
   }

   /**
    * Gets the value of the path property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getPath()
   {
      return path;
   }

   /**
    * Sets the value of the path property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setPath(String value)
   {
      this.path = value;
   }

   /**
    * Gets the value of the repeating property.
    * 
    * @return
    *     possible object is
    *     {@link Boolean }
    *     
    */
   public boolean isRepeating()
   {
      if (repeating == null)
      {
         return false;
      }
      else
      {
         return repeating;
      }
   }

   /**
    * Sets the value of the repeating property.
    * 
    * @param value
    *     allowed object is
    *     {@link Boolean }
    *     
    */
   public void setRepeating(Boolean value)
   {
      this.repeating = value;
   }

   /**
    * Gets the value of the required property.
    * 
    * @return
    *     possible object is
    *     {@link Boolean }
    *     
    */
   public boolean isRequired()
   {
      if (required == null)
      {
         return false;
      }
      else
      {
         return required;
      }
   }

   /**
    * Sets the value of the required property.
    * 
    * @param value
    *     allowed object is
    *     {@link Boolean }
    *     
    */
   public void setRequired(Boolean value)
   {
      this.required = value;
   }

   /**
    * Gets the value of the style property.
    * 
    * @return
    *     possible object is
    *     {@link ParamStyle }
    *     
    */
   public ParamStyle getStyle()
   {
      return style;
   }

   /**
    * Sets the value of the style property.
    * 
    * @param value
    *     allowed object is
    *     {@link ParamStyle }
    *     
    */
   public void setStyle(ParamStyle value)
   {
      this.style = value;
   }

   /**
    * Gets the value of the type property.
    * 
    * @return
    *     possible object is
    *     {@link QName }
    *     
    */
   public QName getType()
   {
      if (type == null)
      {
         return new QName("http://www.w3.org/2001/XMLSchema", "xs");
      }
      else
      {
         return type;
      }
   }

   /**
    * Sets the value of the type property.
    * 
    * @param value
    *     allowed object is
    *     {@link QName }
    *     
    */
   public void setType(QName value)
   {
      this.type = value;
   }

   /**
    * Gets a map that contains attributes that aren't bound to any typed property on this class.
    * 
    * <p>
    * the map is keyed by the name of the attribute and 
    * the value is the string value of the attribute.
    * 
    * the map returned by this method is live, and you can add new attribute
    * by updating the map directly. Because of this design, there's no setter.
    * 
    * 
    * @return
    *     always non-null
    */
   public Map<QName, String> getOtherAttributes()
   {
      return otherAttributes;
   }

}
