# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1279798415);
user_pref("app.update.lastUpdateTime.background-update-timer", 1279798414);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1279798414);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1279798416);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1279798433);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1279798417);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.useDownloadDir", true);
user_pref("browser.download.dir", "@@@@@@");
user_pref("browser.download.lastDir", "@@@@@@");
user_pref("browser.download.manager.showWhenStarting",false);
user_pref("browser.download.folderList", 2);
user_pref("browser.download.manager.closeWhenDone",true);
user_pref("browser.download.manager.useWindow",false);
user_pref("browser.download.show_plugins_in_list",false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.11");
user_pref("browser.startup.page", 0);
user_pref("extensions.enabledItems", "gwt-dev-plugin@google.com:1.0.7511,httpanalyzerffaddonv5@ieinspector.com:5.0.1,jqs@sun.com:1.0,{a6fd85ed-e919-4a43-a5af-8da18bda539f}:1.0.7,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.11");
user_pref("extensions.lastAppVersion", "3.5.11");
user_pref("extensions.newAddons", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.autoScroll", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1282390616);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
